---
- name: config test mode
  hosts: bootnode
  gather_facts: true
  become: true
  roles:
  - bootnode

- name: config test mode
  hosts: all
  gather_facts: true
  become: true
  roles:
  - base_linux


  

  