---
- name: apply flannel
  hosts:
  - bootnode
  gather_facts: true
  tasks:
    ## flannelのコピー
    #
    - set_fact:
        interface: enp0s8
      when:
        - ansible_facts.distribution == "Ubuntu"
    - set_fact:
        interface: eth1
      when:
       - ansible_facts.distribution == "CentOS"
  
    - name: copy a manifest of Flannel for k8s ver > 11
      template:
        src:  kube-flannel.yml.j2
        dest: /home/vagrant/kube-flannel.yml
        mode: 0644
        owner: vagrant
        group: vagrant

    - name: Deploy Flannel
      shell: |
        kubectl apply -f kube-flannel.yml > /home/vagrant/kubectl_apply_flannel.log
      args:
        chdir: /home/vagrant
      become_user: vagrant

