- name: k8s base install
  hosts:
  - masters
  - nodes
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - kubernetes

- name: HA-PROXY install
  hosts:
  - mlbs
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy

- name: K8s Master 1st node setup
  hosts: master1
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - master

- name: apply flannel
  hosts:
  - bootnode
  gather_facts: true
  tasks:

    - name: copy config to home dir
      copy:
        src:  /mnt/k8s-config/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes    
        owner: vagrant
        group: vagrant
        mode:  '0600'

    ## flannelのコピー
    #
    - set_fact:
        interface: enp0s8
      when:
        - ansible_facts.distribution == "Ubuntu"
    - set_fact:
        interface: eth1
      when:
       - ansible_facts.distribution == "CentOS"
  
    - name: copy a manifest of Flannel for k8s ver > 11
      template:
        src:  kube-flannel.yml.j2
        dest: /home/vagrant/kube-flannel.yml
        mode: 0644
        owner: vagrant
        group: vagrant

    - name: Deploy Flannel
      shell: |
        kubectl apply -f kube-flannel.yml > /home/vagrant/kubectl_apply_flannel.log
      args:
        chdir: /home/vagrant
      become_user: vagrant

- name: K8s Master 2nd node setup
  hosts:
  - master2
  - master3
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - master2

- name: K8s Worker node setup
  hosts: nodes
  gather_facts: true
  become: true
  roles:
    - node

- name: K8s Monitoring setup
  hosts: bootnode
  gather_facts: true
  become: true
  roles:
    - monitoring
