##
##　追加のコントロールプレーン用
##　


## k8sの設定をリセット
##
- name: kubeadm reset
  command: kubeadm reset -f


## 証明書等を1stマスターからコピーする
##
- name: copy pki files from 1st master
  file:
    path: /etc/kubernetes/pki
    state: directory
    recurse: yes
    owner: root
    group: root
- file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    recurse: yes
    owner: root
    group: root
- shell: |
    cp /mnt/k8s-pki/ca.crt /etc/kubernetes/pki
    cp /mnt/k8s-pki/ca.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/sa.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/sa.pub /etc/kubernetes/pki
    cp /mnt/k8s-pki/front-proxy-ca.crt /etc/kubernetes/pki
    cp /mnt/k8s-pki/front-proxy-ca.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/etcd-ca.crt /etc/kubernetes/pki/etcd/ca.crt
    cp /mnt/k8s-pki/etcd-ca.key /etc/kubernetes/pki/etcd/ca.key
    #cp /mnt/k8s-pki/etcd.crt /etc/kubernetes/pki/etcd/server.crt
    #cp /mnt/k8s-pki/etcd.key /etc/kubernetes/pki/etcd/server.key    
    cp /mnt/k8s-pki/admin.conf /etc/kubernetes
    chown -R root:root /etc/kubernetes
    chmod 0600 /etc/kubernetes/pki/*
    chmod 0644 /etc/kubernetes/pki/*.crt
    exit 0


## k8sクラスタへマスターとして参加するための構成ファイル作成
##
- name: remove /tmp/kubeadm-config.yaml
  file:
    path: "/tmp/kubeadm-config.yaml"
    state: absent

- name: copy from home to local
  copy:
    src: "/mnt/k8s-config/kubeadm-config-for-join.tmp"
    dest: "/tmp/kubeadm-config.yaml"

- name: change IP address & hostname
  replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__NODE_IP_ADDR__'
    replace: "{{ ansible_facts.enp0s8.ipv4.address }}"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__NODE_HOSTNAME__'
    replace: "{{ ansible_facts.hostname }}"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__LB_IP_ADDR__'
    replace: "172.16.2.21"

- name: import token for join
  include_vars: "/mnt/k8s-config/token.yaml"
- include_vars: "/mnt/k8s-config/discovery-token-ca-cert-hash.yaml"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__TOKEN__'
    replace: "{{ token }}"


## 2nd マスターノードの構成
##
#- name: build 2nd master nodes
#  shell: kubeadm join --config /tmp/kubeadm-config.yaml
#  register: join_result
#- debug: msg="2nd master = {{ join_result }}"

###########
- name: include kubeadm join token etc
  include_vars: /mnt/k8s-config/kubeadm-join-master.tmp
#- command: "{{ join_command }}"  
###########

## kubeletのDNSのIPアドレスを変更
##
- include_tasks: tasks/change_kubelet_dns.yml

## kubeconfigディレクトリ作成
#
- include_tasks: tasks/kubeconfig_setup.yml

