#
# ブートノードの設定
#
#- debug: msg="{{ ansible_facts.hostname }}"

- name: Install a list
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-kernel-server
    - emacs-nox

- name: mkdir for nfs exports
  file:
    path:  /srv/k8s
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0777'

- name: mkdir for ssh keys
  file:
    path:  /srv/k8s/keys
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0777'

- name: mkdir for cluster config & cert file
  file:
    path:  /srv/k8s/k8s-config
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0777'


- name: mkdir for cluster config & cert file
  file:
    path:  /srv/k8s/k8s-pki
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0777'

- name: mkdir kubeconfig
  file:
    path:  /srv/k8s/kubeconfig
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0777'

- name: mkdir download
  file:
    path:  /srv/k8s/download
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0777'

- name: re-start nfs server
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: install nfs exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
- command: exportfs -a


#############################
- name: Install ansible code from git repo
  git:
    repo: https://github.com/takara9/vagrant-kubernetes
    dest: /home/vagrant/k8s
    version: k8s_tm
    force: yes
    update: yes
  become_user: vagrant    

#- name: copy config template for join
#  copy:
#    src:  /home/vagrant/k8s/k8s-config/kubeadm-config-for-join.tmp
#    dest: /srv/k8s/k8s-config/kubeadm-config-for-join.tmp
#    owner: vagrant
#    group: vagrant
#    mode: '0644'

#- name: copy config template for init
#  copy:
#    src:  /home/vagrant/k8s/k8s-config/kubeadm-config.tmp
#    dest: /srv/k8s/k8s-config/kubeadm-config.tmp
#    owner: vagrant
#    group: vagrant
#    mode: '0644'


#############################
- name: mkdir .ssh directory
  file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: '0700'
- name: keygen
  command: ssh-keygen -t rsa -N '' -f .ssh/id_rsa
  args:
    chdir: /root
    
- name: Copy id_rsa.pub to  shared_fs keys
  command: cp /root/.ssh/id_rsa.pub /srv/k8s/keys/id_rsa.pub
- file:
    path: /srv/k8s/keys/id_rsa.pub
    owner: root
    group: root
    mode: '0444'
- name: Copy id_rsa to  shared_fs/keys
  command: cp /root/.ssh/id_rsa /srv/k8s/keys/id_rsa
- file:
    path: /srv/k8s/keys/id_rsa
    owner: root
    group: root
    mode: '0444'

- name: Create authorized_keys
  command: cp /srv/k8s/keys/id_rsa.pub  /root/.ssh/authorized_keys
- file:
    path: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: '0400'

##################################
- name: add Kubernetes apt-key [ubuntu]
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository [ubuntu]
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install kubectl [ubuntu]
  apt:
    name: kubectl{{ k8s_version_ubuntu }}
    state: present


