##
##　追加のコントロールプレーン用
##　
##
## k8sの設定をリセット
#
- name: kubeadm reset
  command: kubeadm reset -f

## 証明書等を1stマスターからコピーする
- name: copy pki files from 1st master
  file:
    path: /etc/kubernetes/pki
    state: directory
    recurse: yes
    owner: root
    group: root
- file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    recurse: yes
    owner: root
    group: root


- shell: |
    #cp /mnt/k8s-pki/ca.crt /etc/kubernetes/pki
    cp /mnt/k8s-pki/ca.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/sa.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/sa.pub /etc/kubernetes/pki
    cp /mnt/k8s-pki/front-proxy-ca.crt /etc/kubernetes/pki
    cp /mnt/k8s-pki/front-proxy-ca.key /etc/kubernetes/pki
    cp /mnt/k8s-pki/etcd-ca.crt /etc/kubernetes/pki/etcd/ca.crt
    cp /mnt/k8s-pki/etcd-ca.key /etc/kubernetes/pki/etcd/ca.key
    #cp /mnt/k8s-pki/etcd.crt /etc/kubernetes/pki/etcd/server.crt
    #cp /mnt/k8s-pki/etcd.key /etc/kubernetes/pki/etcd/server.key    
    cp /mnt/k8s-pki/admin.conf /etc/kubernetes
    chown -R root:root /etc/kubernetes
    chmod 0600 /etc/kubernetes/pki/*
    chmod 0644 /etc/kubernetes/pki/*.crt
    exit 0

## k8sクラスタへマスターとして参加
#


- name: copy from home to local
  copy:
    src: "/mnt/k8s-config/kubeadm-config-for-join.tmp"
    dest: "/tmp/kubeadm-config.yaml"
#- copy:
#    src: "/mnt/k8s-config/kubeadm-config-for-join.tmp"
#    dest: "/tmp/kubeadm-join-master.yaml"

- name: change IP address & hostname
  replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__NODE_IP_ADDR__'
    replace: "{{ ansible_facts.enp0s8.ipv4.address }}"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__NODE_HOSTNAME__'
    replace: "{{ ansible_facts.hostname }}"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__LB_IP_ADDR__'
    replace: "172.16.2.21"

- name: import token for join
  include_vars: "/mnt/k8s-config/token.yaml"
- include_vars: "/mnt/k8s-config/discovery-token-ca-cert-hash.yaml"
- replace:
    dest: "/tmp/kubeadm-config.yaml"
    regexp: '__TOKEN__'
    replace: "{{ token }}"


#- name: include kubeadm join token etc
#  #include_vars: "/tmp/kubeadm-join-master.yaml"
#  include_vars: "/mnt/k8s-config/kubeadm-join-master.tmp"
- debug: msg="token = {{ token }}"
#- debug: msg="discovery_token_ca_cert_hash = {{ discovery_token_ca_cert_hash }} "
- debug: msg="kubeadm join --config /tmp/kubeadm-config.yaml --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }}"
#- name: kubeadm join for control plane
#  shell: kubeadm join --config /tmp/kubeadm-config.yaml --discovery-token-ca-cert-hash "{{ discovery_token_ca_cert_hash }}"

- name: kubeadm join for control plane
  shell: kubeadm join --config /tmp/kubeadm-config.yaml


## kubeletのDNSのIPアドレスを変更
#
- name: change config.yaml
  replace:
    dest: /var/lib/kubelet/config.yaml
    regexp: '10.96.0.10'
    replace: 10.32.0.10

## kubeletをリスタートして変更を反映
#
- name: daemon-reload and restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    
## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0755'

#- name: mkdir /vagrant/kubeconfig
#  file:
#    path:  /vagrant/kubeconfig
#    state: directory
#    owner: vagrant
#    group: vagrant
#    mode:  '0755'

##  configファイルのコピー
#
#- name: chmod admin.conf
#  file:
#    path:  /etc/kubernetes/admin.conf
#    owner: vagrant
#    group: vagrant
#    mode:  '0600'
    
- name: copy config to home dir
  copy:
    src:  /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes    
    owner: vagrant
    group: vagrant
    mode:  '0600'

