##
##　追加のコントロールプレーン用
##　
##
## k8sの設定をリセット
#
- name: kubeadm reset
  command: kubeadm reset -f

## 証明書等を1stマスターからコピーする
- name: copy pki files from 1st master
  file:
    path: /etc/kubernetes/pki
    state: directory
    recurse: yes
    owner: root
    group: root
    
- shell: |
    cp /vagrant/k8s-pki/ca.crt /etc/kubernetes/pki
    cp /vagrant/k8s-pki/ca.key /etc/kubernetes/pki
    cp /vagrant/k8s-pki/sa.key /etc/kubernetes/pki
    cp /vagrant/k8s-pki/sa.sub /etc/kubernetes/pki
    cp /vagrant/k8s-pki/front-proxy-ca.crt /etc/kubernetes/pki
    cp /vagrant/k8s-pki/front-proxy-ca.key /etc/kubernetes/pki
    cp /vagrant/k8s-pki/etcd-ca.crt /etc/kubernetes/pki/etcd/ca.crt
    cp /vagrant/k8s-pki/etcd-ca.key /etc/kubernetes/pki/etcd/ca.key
    cp /vagrant/k8s-pki/admin.conf /etc/kubernetes
    chown -R root:root /etc/kubernetes
    chmod 0600 /etc/kubernetes/pki/*
    chmod 0644 /etc/kubernetes/pki/*.crt
    exit 0

## k8sクラスタへマスターとして参加
#
- name: copy from home to local
  copy:
    src: /vagrant/kubeadm-join-control.tmp
    dest: /tmp/kubeadm-join-control.yaml
- name: include kubeadm join token etc
  include_vars: /tmp/kubeadm-join-control.yaml
- name: kubeadm join
  command: "{{ ctrl_join_command }}"  


## kubeletのDNSのIPアドレスを変更
#
- name: change config.yaml
  replace:
    dest: /var/lib/kubelet/config.yaml
    regexp: '10.96.0.10'
    replace: 10.32.0.10

## kubeletをリスタートして変更を反映
#
- name: daemon-reload and restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    
## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0755'

- name: mkdir /vagrant/kubeconfig
  file:
    path:  /vagrant/kubeconfig
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0755'

##  configファイルのコピー
#
- name: chmod admin.conf
  file:
    path:  /etc/kubernetes/admin.conf
    owner: vagrant
    group: vagrant
    mode:  '0600'
    
- name: copy config to home dir
  copy:
    src:  /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode:  '0600'

