## Metrics Server インストール
#
- name: Install Metrics Server
  git:
    repo: 'https://github.com/kubernetes-sigs/metrics-server'
    dest: /home/vagrant/metrics-server
    force: yes
  #become_user: vagrant    

- name: add a new line
  blockinfile:
    path: /home/vagrant/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml
    insertafter: '        args:'
    block: |
           # added lines
                     - --kubelet-insecure-tls
                     - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname

#- name: Deploy Metrics Server
#  command: kubectl apply -f metrics-server/deploy/kubernetes
#  become_user: vagrant
#  args:
#    chdir: /home/vagrant
#- name: Deploy Metrics Server
#  k8s:
#    state: present
#    src: "{{ manifest_dir }}/aggregated-metrics-reader.yaml"
#    apply: yes
#    kubeconfig: /etc/kubernetes/admin.conf
#vars:
#    manifests:
#    - "{{ manifest_dir }}/aggregated-metrics-reader.yaml"
#    - "{{ manifest_dir }}/auth-delegator.yaml"
#    - "{{ manifest_dir }}/auth-reader.yaml"
#    - "{{ manifest_dir }}/metrics-apiservice.yaml"
#    - "{{ manifest_dir }}/metrics-server-deployment.yaml"
#    - "{{ manifest_dir }}/metrics-server-service.yaml"
#    - "{{ manifest_dir }}/resource-reader.yaml"


- name: Deploy Metrics Server
  k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/aggregated-metrics-reader.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/auth-delegator.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/auth-reader.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/metrics-apiservice.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/metrics-server-deployment.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/metrics-server-service.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf
- k8s:
    state: present
    src: /home/vagrant/metrics-server/deploy/kubernetes/resource-reader.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf





## Dashboard UI インストール
#
- name: Download Dashboard Manifest
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml
    dest: /home/vagrant/
    mode: '0644'
    owner: vagrant
    group: vagrant
- name: Change Dashboard RBAC
  replace:
    path: /home/vagrant/recommended.yaml
    after: '  kind: ClusterRole'
    regexp: '^  name: kubernetes-dashboard'
    replace: '  name: cluster-admin'
- name: Deploy Dashboard UI
#  become_user: vagrant
#  command: kubectl apply -f /home/vagrant/recommended.yaml
  k8s:
    state: present
    src: /home/vagrant/recommended.yaml
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf


- name: setup kubeconfig
  become_user: vagrant    
  shell: |
        KUBECONFIG=/etc/kubernetes/admin.conf 
        TOKEN=$(kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret |grep kubernetes-dashboard-token-* | awk '{print $1}') |awk '$1=="token:"{print $2}')
        kubectl config set-credentials kubernetes-admin --token="${TOKEN}"


- name: copy config to host dir
  copy:
    src:  /home/vagrant/.kube/config
    dest: /vagrant/kubeconfig/config
    owner: vagrant
    group: vagrant
    mode:  '0600'
